gd_account_name: "haryobagasasyafah6@gmail"
gd_root_folder_id: "0ACR-6T834uGQUk9PVA"

sync_target_path: "/home/bearaujus/minecraft-server"
sync_delay_minute: 300
sync_worker: 50
sync_retry: 5

test_mode: false
test_mode_op_delay_ms: 300
